apiVersion: apps/v1
kind: Deployment
metadata:
  name: clinical-data-service
  namespace: clinical-platform
spec:
  replicas: 3
  selector:
    matchLabels:
      app: clinical-data-service
  template:
    metadata:
      labels:
        app: clinical-data-service
    spec:
      containers:
      - name: clinical-data-service
        image: clinical-platform/clinical-data-service:1.0.0
        ports:
        - containerPort: 8081
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "kubernetes"
        - name: DB_HOST
          value: "postgres-service"
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
        livenessProbe:
          httpGet:
            path: /api/v1/actuator/health
            port: 8081
          initialDelaySeconds: 60
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /api/v1/actuator/health
            port: 8081
          initialDelaySeconds: 30
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: clinical-data-service
  namespace: clinical-platform
spec:
  selector:
    app: clinical-data-service
  ports:
  - port: 8081
    targetPort: 8081
  type: ClusterIP