-- Initialize PostgreSQL with pgvector extension for Clinical Analytics Platform
-- This script sets up the vector database for AI/ML operations

-- Create database
CREATE DATABASE clinical_analytics;

-- Connect to the database
\c clinical_analytics;

-- Create user
CREATE USER clinical_user WITH PASSWORD 'clinical_password';
GRANT ALL PRIVILEGES ON DATABASE clinical_analytics TO clinical_user;

-- Install pgvector extension
CREATE EXTENSION IF NOT EXISTS vector;
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- Create schema for vector operations
CREATE SCHEMA IF NOT EXISTS clinical_vectors;
GRANT ALL ON SCHEMA clinical_vectors TO clinical_user;

-- Create clinical records table
CREATE TABLE clinical_records (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    patient_id VARCHAR(50) NOT NULL,
    patient_age INTEGER,
    patient_gender VARCHAR(20),
    bmi DECIMAL(5,2),
    heart_rate INTEGER,
    systolic_bp DECIMAL(5,2),
    diastolic_bp DECIMAL(5,2),
    temperature DECIMAL(4,1),
    clinical_narrative TEXT,
    symptoms TEXT[],
    medications TEXT[],
    record_type VARCHAR(50),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Create vector embeddings table for semantic search
CREATE TABLE clinical_vectors.clinical_embeddings (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    content TEXT NOT NULL,
    metadata JSONB,
    embedding vector(384), -- 384 dimensions for all-MiniLM-L6-v2 model
    record_id UUID REFERENCES clinical_records(id),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Create indexes for performance
CREATE INDEX idx_clinical_records_patient_id ON clinical_records(patient_id);
CREATE INDEX idx_clinical_records_type ON clinical_records(record_type);
CREATE INDEX idx_clinical_records_created_at ON clinical_records(created_at);

-- Create HNSW index for vector similarity search
CREATE INDEX idx_clinical_embeddings_vector ON clinical_vectors.clinical_embeddings 
USING hnsw (embedding vector_cosine_ops) WITH (m = 16, ef_construction = 64);

CREATE INDEX idx_clinical_embeddings_metadata ON clinical_vectors.clinical_embeddings 
USING GIN (metadata);

-- Grant permissions
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO clinical_user;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA clinical_vectors TO clinical_user;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO clinical_user;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA clinical_vectors TO clinical_user;

-- Insert sample clinical data for ML training
INSERT INTO clinical_records (patient_id, patient_age, patient_gender, bmi, heart_rate, systolic_bp, diastolic_bp, temperature, clinical_narrative, symptoms, medications, record_type) VALUES
('P001', 45, 'male', 28.5, 85, 140.0, 90.0, 98.6, 'Patient presents with chest pain and shortness of breath. History of hypertension and diabetes.', ARRAY['chest pain', 'shortness of breath'], ARRAY['lisinopril', 'metformin'], 'DIAGNOSIS'),
('P002', 62, 'female', 32.1, 92, 160.0, 95.0, 99.2, 'Diabetic patient with poor glycemic control. Presenting with fatigue and frequent urination.', ARRAY['fatigue', 'polyuria', 'polydipsia'], ARRAY['insulin', 'metformin'], 'DIAGNOSIS'),
('P003', 38, 'male', 24.8, 78, 125.0, 82.0, 98.4, 'Young adult with anxiety and panic attacks. No significant medical history.', ARRAY['anxiety', 'palpitations'], ARRAY['sertraline'], 'DIAGNOSIS'),
('P004', 55, 'female', 29.7, 88, 145.0, 88.0, 98.8, 'Postmenopausal woman with osteoporosis and joint pain. Family history of heart disease.', ARRAY['joint pain', 'back pain'], ARRAY['calcium', 'vitamin D'], 'DIAGNOSIS'),
('P005', 71, 'male', 26.3, 95, 155.0, 92.0, 99.1, 'Elderly patient with COPD and smoking history. Presenting with chronic cough and dyspnea.', ARRAY['chronic cough', 'dyspnea'], ARRAY['albuterol', 'prednisone'], 'DIAGNOSIS');

-- Insert sample vector embeddings (simplified - in real implementation, these would be generated by ML models)
INSERT INTO clinical_vectors.clinical_embeddings (content, metadata, embedding, record_id) 
SELECT 
    clinical_narrative,
    jsonb_build_object(
        'patient_id', patient_id,
        'record_type', record_type,
        'age', patient_age,
        'gender', patient_gender,
        'symptoms', symptoms
    ),
    -- Generate random embeddings for demo (in production, use actual ML model)
    (SELECT ARRAY(SELECT random() FROM generate_series(1, 384)))::vector,
    id
FROM clinical_records;

-- Create function for similarity search
CREATE OR REPLACE FUNCTION search_similar_cases(
    query_embedding vector(384),
    similarity_threshold float DEFAULT 0.8,
    max_results int DEFAULT 10
)
RETURNS TABLE (
    record_id UUID,
    content TEXT,
    metadata JSONB,
    similarity_score float
) AS $$
BEGIN
    RETURN QUERY
    SELECT 
        ce.record_id,
        ce.content,
        ce.metadata,
        1 - (ce.embedding <=> query_embedding) as similarity_score
    FROM clinical_vectors.clinical_embeddings ce
    WHERE 1 - (ce.embedding <=> query_embedding) > similarity_threshold
    ORDER BY ce.embedding <=> query_embedding
    LIMIT max_results;
END;
$$ LANGUAGE plpgsql;

-- Create function for clinical risk assessment
CREATE OR REPLACE FUNCTION calculate_population_risk(
    age_min int DEFAULT 0,
    age_max int DEFAULT 120
)
RETURNS TABLE (
    risk_category TEXT,
    patient_count BIGINT,
    avg_systolic_bp DECIMAL,
    avg_bmi DECIMAL
) AS $$
BEGIN
    RETURN QUERY
    SELECT 
        CASE 
            WHEN cr.patient_age < 40 THEN 'Low Risk'
            WHEN cr.patient_age BETWEEN 40 AND 65 THEN 'Moderate Risk'
            ELSE 'High Risk'
        END as risk_category,
        COUNT(*) as patient_count,
        AVG(cr.systolic_bp) as avg_systolic_bp,
        AVG(cr.bmi) as avg_bmi
    FROM clinical_records cr
    WHERE cr.patient_age BETWEEN age_min AND age_max
    GROUP BY risk_category
    ORDER BY risk_category;
END;
$$ LANGUAGE plpgsql;

-- Create materialized view for analytics
CREATE MATERIALIZED VIEW clinical_analytics_summary AS
SELECT 
    record_type,
    COUNT(*) as total_records,
    AVG(patient_age) as avg_age,
    AVG(bmi) as avg_bmi,
    AVG(systolic_bp) as avg_systolic_bp,
    COUNT(DISTINCT patient_id) as unique_patients
FROM clinical_records
GROUP BY record_type;

-- Create index on materialized view
CREATE INDEX idx_clinical_analytics_summary_type ON clinical_analytics_summary(record_type);

-- Grant permissions on functions and views
GRANT EXECUTE ON FUNCTION search_similar_cases(vector, float, int) TO clinical_user;
GRANT EXECUTE ON FUNCTION calculate_population_risk(int, int) TO clinical_user;
GRANT SELECT ON clinical_analytics_summary TO clinical_user;

-- Create trigger to refresh materialized view
CREATE OR REPLACE FUNCTION refresh_clinical_analytics()
RETURNS TRIGGER AS $$
BEGIN
    REFRESH MATERIALIZED VIEW clinical_analytics_summary;
    RETURN NULL;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trigger_refresh_analytics
    AFTER INSERT OR UPDATE OR DELETE ON clinical_records
    FOR EACH STATEMENT
    EXECUTE FUNCTION refresh_clinical_analytics();

COMMIT;